target_repository:
  HTTPS: https://github.com/PyTorchLightning/lightning-flash.git
  # checkout a particular branch or a tag
  checkout: master
  # define installing package extras
  install_extras: image,text,tabular,test
  # copy some  test from the target repository
  copy_tests:
    - flash_examples
    - tests/__init__.py
    - tests/helpers
    - tests/examples/__init__.py
    - tests/examples/utils.py
    - tests/examples/test_scripts.py

contact:
  slack:
    # Ethan Harris
    - USPB6E0LF

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/PyTorchLightning/pytorch-lightning.git
    checkout: release/stable
    # install_extras: all

testing:
  dirs:
    - tests/examples
  # additional pytest arguments
  pytest_args: --strict

runtimes:
  - {os: "ubuntu-20.04", python-version: "3.8"}
  - {os: "macOS-10.15", python-version: "3.8"}
  - {os: "windows-2019", python-version: "3.8"}
