target_repository:
  HTTPS: https://github.com/PyTorchLightning/lightning-transformers.git
  # checkout a particular branch or a tag
  checkout: master
  # define installing package extras
  install_extras: all
  # copy some  test from the target repository
  copy_tests:
    - tests
    - tests/__init__.py

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/PyTorchLightning/pytorch-lightning.git
    checkout: release/1.5.x
    # install_extras: all

testing:
  dirs:
    - tests
