source_repository:
  HTTPS: https://github.com/Lightning-AI/lightning-flash.git
  # checkout a particular branch or a tag
  checkout: master
  # define installing package extras
  install_extras: image,text,tabular
  # copy some  test from the target repository
  copy_tests:
    - examples
    - tests/__init__.py
    - tests/helpers
    - tests/examples/__init__.py
    - tests/examples/utils.py
    - tests/examples/test_scripts.py

contact:
  slack:
    # Kushashwa Ravi Shrimali
    - U030AS8BRCY

env:
  # let's limit the installation only to Pytorch-Lightning
  PACKAGE_NAME: pytorch

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/Lightning-AI/lightning.git
    checkout: master
    # install_extras: all
  - name: torchmetrics
    HTTPS: https://github.com/Lightning-AI/metrics.git
    checkout: master
    # install_extras: all
  - name: pytest-forked

testing:
  dirs:
    - tests/examples
  # additional pytest arguments
  pytest_args: --strict

runtimes:
  - {os: "ubuntu-20.04", python: "3.8"}
