target_repository:
  HTTPS: https://github.com/Lightning-AI/metrics.git
  # OPTIONAL, for some protected repository
  # username: my-nick
  # OPTIONAL, paired with the username
  # password: dont-tell-anyone
  # OPTIONAL, overrides the user/pass
  # token: authentication-token
  # OPTIONAL, checkout a particular branch or a tag
  checkout: master
  # OPTIONAL, define installing package extras
  install_extras: all
  # OPTIONAL, install additional requirements from a file
  # requirements_file: requirements.txt
  # passing additional `pip install` flags
  install_flags: "--use-pep517"
  # copy some  test from the target repository
  copy_tests:
    - integrations
    - tests/__init__.py
    - tests/helpers

contact:
  slack:
    - borda
  email: []

# OPTIONAL, running before installing your project
# WARNING: this is custom for given OS, we do not manage any inter OS compatibility
before_install:
  - pip install "Cython>=0.29"

# OPTIONAL, if any installation require some env. variables
env:
  PACKAGE_NAME: "pytorch"

dependencies:
  - name: pytorch-lightning
    HTTPS: https://github.com/Lightning-AI/lightning.git
    checkout: release/stable
    # install_extras: all
  - name: typing_extensions
    checkout: 4.1.1
    install_flags: "--use-pep517"

# OPTIONAL, running before installing your project
# WARNING: this is custom for given OS, we do not manage any inter OS compatibility
before_test:
  - wget https://pl-flash-data.s3.amazonaws.com/titanic.zip

testing:
  dirs:
    - integrations
  # OPTIONAL, additional pytest arguments
  pytest_args: --strict

runtimes:
  - {os: "ubuntu-20.04", python: "3.9"}
  - {os: "macOS-10.15", python: "3.7"}
  - {os: "windows-2019", python: "3.8"}
